-- companion_content seed
-- Generated by scripts/generate-companion-seed.js
-- Generated: 2026-05-31T22:48:18.329Z
-- DO NOT EDIT by hand — edit the content files and re-run the generator.

-- ─── ANTICIPATORY GUIDANCE (AG) ──────────────────────────────────

INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-001',
  'Colostrum: small amounts are exactly right',
  'Your baby''s stomach is the size of a marble right now — that''s not an exaggeration. The colostrum your body is making is exactly the right amount and exactly the right nutrition for this stage. If it feels like almost nothing is coming out, that''s completely normal. Want me to explain what''s happening?',
  'Colostrum is a concentrated, low-volume first milk that your body produces for the first 24–72 hours. A newborn''s stomach capacity on day one is roughly 5–7 mL per feeding — about one teaspoon. Colostrum is dense in antibodies (especially secretory IgA), white blood cells, and growth factors that protect the newborn gut before mature milk arrives. Its low volume is physiologically intentional: it helps the baby learn to coordinate sucking and swallowing before higher milk flow begins. Feeding on demand in these early hours — at least 8–12 times per 24 hours — signals your body to ramp up milk production. Frequent feeding now is the single most important thing you can do for long-term supply. Source: ABM Protocol #2; AAP Section on Breastfeeding 2022; LLLI "Breastfeeding in the Early Days."',
  'If your baby is not waking to feed at least every 3 hours, seems lethargic or difficult to rouse, or has fewer than 1 wet diaper by the end of day 1, contact your pediatrician or lactation consultant before your next scheduled visit.',
  NULL,
  'ABM Protocol #2; AAP 2022 breastfeeding policy; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-002',
  'Your milk is coming in — here''s what that feels like',
  'Somewhere between days 3 and 5, your milk "comes in" — meaning your body transitions from colostrum to mature milk. Your breasts may feel very full, hard, or warm. This can be uncomfortable. It''s normal. It''s also temporary. Want to know what to do and what to watch for?',
  'The transition from colostrum to mature milk is driven by the drop in progesterone that follows delivery of the placenta. Breasts typically become noticeably fuller, heavier, and sometimes rock-hard — this is called engorgement, and it usually peaks around days 3–5 and eases within 24–48 hours as your body calibrates to your baby''s demand. To manage engorgement: feed or pump frequently (every 2–3 hours), apply a warm compress for a few minutes before feeding to encourage letdown, and use a cold compress after to reduce swelling. For nursing moms, ensuring a deep latch is especially important when breasts are engorged — a shallow latch on a very full breast is painful and inefficient. For pumping moms, pump to comfort (not to empty) during peak engorgement to avoid signaling your body to overproduce. Sources: ABM Protocol #20; LLLI "Engorgement"; ABM Protocol #2.',
  'Engorgement that does not improve with frequent feeding or pumping within 48 hours, or that is accompanied by fever above 100.4°F, redness, or a hard lump in one area, may indicate mastitis or a plugged duct. Contact your care provider the same day.',
  NULL,
  'ABM Protocol #20; ABM Protocol #2; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-003',
  'How to know your baby is getting enough',
  '"Is my baby getting enough?" is the most common question new moms have, and the answer lives in three places: diapers, weight, and behavior. Want me to walk you through exactly what to look for this week?',
  'The most reliable output markers in week one:

Diapers: By day 4–5, expect at least 6 wet diapers and 3–4 yellow seedy stools per 24 hours. Urine should be pale yellow — dark or brick-red (urate crystals) in the first 2–3 days is normal, but should clear by day 4.

Weight: It is normal for newborns to lose up to 7% of birth weight in the first 3–5 days. Most regain birth weight by days 10–14. Your pediatrician will track this at the 2-day and 2-week visits. If your baby has not regained birth weight by 2 weeks, a lactation evaluation is recommended.

Behavior: A well-fed baby will have periods of alertness and will release the breast or bottle spontaneously. A baby who seems constantly hungry, sleepy and hard to wake, or inconsolable after most feedings may not be transferring enough milk.

For pumping moms: pump output alone is not always a reliable indicator of what a baby would transfer directly. A baby typically extracts more efficiently than a pump in the early weeks. Sources: AAP 2022; ABM Protocol #3; LLLI "Is My Baby Getting Enough Milk?"',
  'Contact your pediatrician promptly if: baby has not regained birth weight by 2 weeks, has fewer than 6 wet diapers after day 5, is not waking to feed every 2–3 hours, or seems excessively yellow (jaundiced). These are the main reasons newborns are readmitted in the first 2 weeks.',
  NULL,
  'AAP 2022; ABM Protocol #3; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-004',
  'Nipple pain should be getting better by now',
  'Some nipple tenderness in the first 1–2 weeks is common. By week 2, it should be easing — not getting worse. If latching still hurts, that''s worth looking at before it becomes a bigger problem. Want to talk through what might be going on?',
  'Mild nipple sensitivity is normal in the first 7–10 days as your body adjusts. Persistent or worsening pain after week one — especially pain that shoots, burns, or makes you dread feedings — is almost always a sign that something about the latch or positioning can be improved. The most common causes: latch that''s too shallow (baby taking mostly nipple instead of a good portion of areola), a tight frenulum in the baby (tongue tie), or a poor feeding position that puts uneven pressure on the nipple. A good latch should be asymmetric — more areola visible above the nipple than below — and the baby''s chin should be pressed into the breast. Pain that persists beyond the first 30–60 seconds of a latch, or that is present throughout the entire feed, is not something to push through. An IBCLC can usually identify and correct the issue in one visit. Sources: ABM Protocol #2; LLLI "Sore Nipples"; ABM Protocol #26.',
  'Pain that is getting worse instead of better, cracked or bleeding nipples, white or shiny nipple tips after a feed, or shooting breast pain between feedings are all reasons to see an IBCLC rather than wait.',
  NULL,
  'ABM Protocol #2; ABM Protocol #26; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-005',
  'Get ready: the week 3 growth spurt is coming',
  'Around week 2–3, most babies hit their first major growth spurt. Your baby may seem like they want to eat constantly, act fussier than usual, and make you feel like your supply suddenly disappeared. It didn''t. Here''s what''s actually happening.',
  'Growth spurts are periods of accelerated developmental growth during which babies increase feeding frequency dramatically — sometimes nursing or feeding every 45–60 minutes for 24–48 hours. This behavior is called cluster feeding, and it''s biologically intentional: the baby is signaling your body to increase milk production to meet their growing needs. Common timing: around weeks 2–3, 6–8, and 10–12, with some variation.

What to do: follow the baby''s cues and feed on demand. Trying to space out feeds during a growth spurt to "save up" milk is counterproductive — it signals your body to produce less, not more. For pumping moms, you may need to add one or two pump sessions per day during the spurt. The increased demand is temporary — most cluster feeding phases last 2–4 days.

What this is not: a sign that you don''t have enough milk, that your milk isn''t satisfying enough, or that your baby needs formula. Growth spurts are often the moment families abandon breastfeeding when the real need is just more frequent feeding for a few days. Sources: LLLI "Growth Spurts"; ABM Protocol #2.',
  NULL,
  NULL,
  'LLLI; ABM Protocol #2',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-006',
  'Your supply is being established right now',
  'The first 4–6 weeks are when your body sets its long-term milk production baseline. What you do now — how often you feed or pump, and how completely your breasts are drained — is telling your body how much to make for the entire journey. This is worth understanding.',
  'Milk supply operates on a supply-and-demand system regulated by the hormone prolactin. In the early weeks, prolactin levels are high and the system is sensitive — frequent, thorough removal of milk sends a strong signal to maintain and increase production. Milk left in the breast signals production to slow. This is why frequent feeding in the first 4–6 weeks is so important: you''re not just feeding today''s baby, you''re calibrating tomorrow''s supply.

For nursing moms: aim for 8–12 feedings per 24 hours. Night feeds matter — prolactin levels are highest between midnight and 6am, so skipping night feeds in this window can meaningfully affect supply.

For pumping moms: the same principle applies. 8–10 pump sessions per 24 hours in weeks 1–6 establishes a higher baseline than fewer, longer sessions. Once supply is established (usually around weeks 6–10), many moms can reduce session frequency.

For combo feeding moms: every nursing session or pump session counts. You''re not in an either/or situation — every time milk is removed, your body gets the signal. Sources: ABM Protocol #2; ABM Protocol #9; Hale''s Medications and Mothers'' Milk; LLLI.',
  NULL,
  NULL,
  'ABM Protocol #2; ABM Protocol #9; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-007',
  'Thinking about introducing a bottle? Timing and technique matter',
  'If you''re planning to introduce a bottle — so a partner can feed, or for returning to work — the window of weeks 3–6 is often recommended. Too early can interfere with latch; too late and some babies resist. There''s also a technique that protects your supply. Want to know more?',
  '"Nipple confusion" — where a baby prefers the bottle and resists the breast — is real but not universal. Bottles flow faster and with less effort than the breast, which can lead some babies to become frustrated with nursing. To reduce this risk:

Timing: most IBCLCs recommend waiting until breastfeeding is well established (usually 3–4 weeks) before introducing a bottle, though some families do it earlier without issue.

Paced bottle feeding: hold the bottle horizontal (not tilted up), let the baby draw the nipple in actively rather than tipping milk in, and allow pauses. This mimics the effort of nursing and slows intake so the baby doesn''t overfeed. Feed responsively — stop when the baby shows satiation cues, regardless of how much is left in the bottle.

For your supply: if you introduce a bottle and miss a nursing session, pump at that same time to maintain the feeding signal to your body.

Bottle nipple choice: slow-flow nipples are recommended for breastfed babies regardless of age, to avoid bottle preference from flow rate differences. Sources: ABM Protocol #2; ABM Protocol #10; LLLI "Introducing a Bottle."',
  NULL,
  NULL,
  'ABM Protocol #2; ABM Protocol #10; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-008',
  'Your breasts may feel softer now — that''s a good sign',
  'Around week 6, many nursing moms notice their breasts feel less full, softer, and don''t seem to "fill up" the same way they used to. This alarms a lot of moms. It almost always means your supply is regulating, not disappearing. Here''s why.',
  'In the early weeks, breasts are producing milk somewhat continuously and often feel noticeably full between feeds. Around weeks 4–6 (timing varies), the supply system shifts: your body transitions from producing milk continuously to producing it more in response to feeding demand — a more efficient, on-demand system. This is called supply regulation.

What it feels like: breasts feel softer, less engorged between feeds, and milk may not spray or drip as noticeably. Some moms also stop feeling as strong a letdown sensation.

What it isn''t: supply dropping. The baby is still getting the same amount of milk — your body is just getting more efficient at producing it on the right schedule. If your baby has normal wet/dirty diapers, is gaining weight appropriately, and seems satisfied after most feeds, your supply is fine.

What to watch: if the softening is accompanied by a sudden change in baby''s weight gain, diaper output, or behavior at the breast, that''s worth checking with your pediatrician or IBCLC. But softness alone, in the context of a thriving baby, is reassuring. Sources: LLLI "Changes in Milk Production"; ABM Protocol #2.',
  NULL,
  NULL,
  'LLLI; ABM Protocol #2',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-009',
  'Second growth spurt: this one often catches people off guard',
  'There''s another growth spurt coming around weeks 6–8 — and it often hits harder than the first because moms feel like they finally had a routine. Your baby may cluster feed again, seem unsatisfied, and be harder to settle. You''ve been here before. You can do this again.',
  'The 6–8 week growth spurt coincides with a significant developmental leap — babies are becoming more visually and socially aware, which also makes them harder to settle at feeds (they''re distracted). At the same time, the cluster feeding signal is real: milk demand is increasing. The approach is the same as week 3: feed on demand, don''t try to schedule through it, add pump sessions if needed for pumping moms. This growth spurt may last slightly longer — sometimes 3–5 days. The good news: after week 8, growth spurts tend to space out and become easier to ride through. Sources: LLLI "Growth Spurts"; ABM Protocol #2.',
  NULL,
  NULL,
  'LLLI; ABM Protocol #2',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-010',
  'Sleep regression + feeding: what to expect',
  'Around 2 months, many babies who were starting to consolidate sleep suddenly start waking more again. This is normal neurological development — not a feeding problem, and not a supply problem. But it affects feeding. Here''s what''s happening.',
  'The 8–10 week period often involves a neurological leap that temporarily disrupts sleep patterns. Babies who were sleeping longer stretches may start waking more frequently at night. This is developmental and temporary — it''s not caused by hunger, insufficient milk, or anything you''re doing wrong.

For breastfeeding and pumping moms: the return of night waking can feel like a setback, but it''s also free supply protection — night feeds stimulate the high-prolactin window. If your baby is waking to feed and feeding well, follow their lead. If you''re pumping and your baby suddenly wants more in the middle of the night, add a session if possible.

For moms who were hoping to drop night feeds around this time: that''s a reasonable goal, but the 8–10 week window is often not the right moment. A few more weeks of patience here is usually the path of least resistance. Sources: AAP safe sleep guidelines; LLLI; published infant sleep development literature.',
  NULL,
  NULL,
  'AAP safe sleep guidelines; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-011',
  'Third growth spurt — but you know how to handle this now',
  'One more growth spurt around weeks 10–12, and then things typically settle into a more predictable rhythm. You''ve navigated two of these already. The pattern is the same — but it usually resolves faster now that your supply is well established.',
  'The 10–12 week growth spurt is typically shorter and less disruptive than the week 3 or week 6–8 spurts, partly because milk supply is more established and responds more efficiently to increased demand. Feed or pump on demand, watch for the usual signs (increased feeding frequency, fussiness, cluster feeding), and expect it to resolve within 2–4 days. After week 12, the breastfeeding relationship often shifts — babies become faster, more efficient feeders, and growth spurts tend to space out to roughly monthly intervals. Many moms describe the 3-month mark as when breastfeeding finally started to feel natural. You''re almost there. Sources: LLLI "Growth Spurts"; ABM Protocol #2.',
  NULL,
  NULL,
  'LLLI; ABM Protocol #2',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-012',
  'Three months in — here''s what changes and what doesn''t',
  'Three months is a real milestone. Feeding typically gets easier and faster from here. Your body knows what it''s doing, your baby is more efficient, and the hardest adjustment period is behind you. Want to know what to expect in the next chapter?',
  'After 3 months, several things typically shift:

Feeding efficiency: babies become faster feeders — sessions that took 30–40 minutes in the early weeks often take 10–15 minutes by month 3. This is normal and not a sign of disinterest or reduced milk transfer.

Distraction: babies become more aware of their surroundings and may pop on and off frequently during feeds. Feeding in quieter environments or using a nursing cover can help for easily distracted babies.

Supply stability: for most moms, supply is well-calibrated by 3 months and is unlikely to drop dramatically without a significant change in feeding frequency. Continuing to feed or pump consistently protects supply going forward.

Solids reminder: the AAP recommends waiting until 6 months (26 weeks) to introduce solid foods for most babies — breast milk or formula should be the primary nutrition until that point. Introducing solids too early can reduce milk intake and supply.

Weaning eventually: when you''re ready, gradual weaning — dropping one feed every few days — is gentler on your body and your baby than stopping abruptly. Sources: AAP 2022; ABM Protocol #2; LLLI.',
  NULL,
  NULL,
  'AAP 2022; ABM Protocol #2; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-013',
  'Returning to work soon? Let''s make a pumping plan',
  'Returning to work while breastfeeding or pumping is doable — but it goes better with a plan made before your first day back, not after. Want to walk through the key things to set up now?',
  'Key things to address before your first day back:

Build a freezer stash: start 2–3 weeks before return. Pump once per day after your first morning feed (when output is typically highest) to accumulate a buffer. You don''t need a huge stash — 3–5 days'' worth is a good working buffer.

Pump at work: under the PUMP Act (2022), most US employers must provide reasonable break time and a private space (not a bathroom) for pumping. Know your rights before you need them. Plan for pump sessions roughly every 3 hours during your work hours — this mirrors your baby''s feeding pattern and protects supply.

Pump bag and supplies: double-check that your pump is fully functional, you have enough flanges and backups for spare parts, and you have a cooler or access to refrigeration at work.

Timing and storage: freshly pumped milk keeps at room temperature for up to 4 hours, in the refrigerator for up to 4 days, and in the freezer for up to 6 months at 0°F. Label bags with date and time.

The first week back is often the hardest emotionally. Many moms feel anxious about supply. The best protection: pump consistently at work, nurse or pump on your normal schedule on non-work days, and give yourself a few weeks before drawing conclusions about supply. Sources: CDC human milk storage guidelines; US PUMP Act 2022; ABM Protocol #2.',
  NULL,
  NULL,
  'CDC milk storage guidelines; US PUMP Act 2022; ABM Protocol #2',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-014',
  '2-week visit coming up — here''s what to ask about feeding',
  'Your baby''s 2-week visit is one of the most important feeding checkpoints. The pediatrician will weigh your baby and assess whether birth weight has been regained. Here''s what to ask so you get the most out of 10 minutes.',
  'Questions worth asking at the 2-week visit:

— Has my baby regained their birth weight? If not, by what date should I expect it, and what should I do in the meantime?
— Is the current diaper output normal for their age and feeding pattern?
— Is there anything in their latch or weight gain pattern that suggests I should see a lactation consultant?
— What weight gain rate should I expect over the next 4 weeks? (Typical: 5–7 oz/week in months 1–3)
— If you''re formula supplementing: is this amount appropriate, and how do I know when to reduce or stop?

Tip: bring a feeding log or share your Latched feeding data if you''ve been tracking. Pediatricians work faster and better with concrete data. Sources: AAP 2022; ABM Protocol #3.',
  'If your baby has not regained birth weight by the 2-week visit, ask specifically what the plan is and what threshold would prompt a lactation referral. Don''t leave without a clear timeline and follow-up plan.',
  NULL,
  'AAP 2022; ABM Protocol #3',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-015',
  '2-month visit: feeding questions worth bringing',
  'The 2-month visit is mostly focused on vaccines, but it''s also a good checkpoint for feeding. Your baby''s weight gain will be reviewed. Here are a few things worth asking while you have the pediatrician''s attention.',
  'Questions for the 2-month visit:

— Is growth on track? (Ask to see the growth curve percentile, not just today''s weight.)
— My baby seems to feed more often some days than others — is that normal? (Yes, usually.)
— Any concerns about my feeding method (nursing / pumping / combo) at this stage?
— If introducing a bottle: any signs of preference issues or feeding aversion to watch for?
— Is my baby''s development consistent with their feeding pattern?

At this visit, pediatricians are also screening for postpartum depression in mothers. If you''re struggling — with feeding, mood, or both — say so directly. You deserve support, and the pediatrician can connect you with resources. Sources: AAP 2022; ABM Protocol #3.',
  NULL,
  NULL,
  'AAP 2022; ABM Protocol #3',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-016',
  'Worried about supply? Let''s look at what''s actually happening',
  'Concerns about supply are one of the most common reasons moms stop breastfeeding earlier than they wanted to — and most of the time, the supply is actually fine. But some supply concerns are real and worth acting on. Let''s figure out which situation you''re in.',
  'The most reliable indicators of adequate supply are your baby''s output and weight — not how your breasts feel, how much you pump, or whether your baby "seems hungry." If your baby has 6+ wet diapers per day, 3+ stools (in the first 6 weeks), and is gaining appropriately at weight checks, your supply is almost certainly adequate.

Common reasons moms perceive low supply that aren''t actually supply issues: breasts feel softer after supply regulates (week 4–6), baby feeds more frequently during growth spurts, baby doesn''t sleep long stretches (not a supply problem), pump output feels low (pump output ≠ feeding output).

Actual supply challenges are less common but do exist. Risk factors include: previous breast surgery, hypoplastic breasts, delayed or infrequent feeding in the first weeks, retained placenta, hormonal conditions (PCOS, thyroid), significant bleeding or hemorrhage at delivery.

If you''re concerned: the most productive first step is a weighted feed or an IBCLC consultation — not adding formula without a plan, and not dramatically changing your feeding pattern based on how full or empty your breasts feel. Sources: ABM Protocol #2; ABM Protocol #9; "Making More Milk" (Marasco & West); LLLI.',
  'If your baby is not gaining weight appropriately, has fewer than 6 wet diapers per day after day 5, or seems lethargic and hard to rouse, contact your pediatrician the same day. These are the signs of actual insufficient intake, not perceived low supply.',
  NULL,
  'ABM Protocol #2; ABM Protocol #9; Marasco & West; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-017',
  'Pain during feeding: let''s figure out what''s going on',
  'Pain during nursing is common — but it''s not something you''re supposed to just push through. Most pain has a fixable cause. Tell me more about what you''re feeling and when, and I can help narrow it down.',
  'Pain during breastfeeding falls into a few distinct categories:

Latch-related pain: sharp pain at latch-on that fades within the first minute is often positional and correctable. Pain that persists throughout the entire feed is usually a deeper latch issue, often involving the baby not taking enough breast tissue or an asymmetric latch. An IBCLC can usually identify and correct this in one visit.

Tongue tie: if latch corrections aren''t helping, a tight frenulum (tongue tie or lip tie) in the baby may be restricting their range of motion at the breast. Assessment by an IBCLC or ENT familiar with infant oral function is appropriate.

Thrush: burning or shooting pain during or between feeds, shiny or white nipple tips, or an itchy nipple are signs of a yeast infection (thrush). Baby may also have white patches in the mouth that don''t wipe off. Thrush requires treatment for both mom and baby simultaneously — see your OB and your baby''s pediatrician.

Vasospasm: white, then blue or purple nipple discoloration after feeds with burning or throbbing pain is vasospasm, often triggered by cold. This is treatable.

Mastitis: painful, warm, hard area in the breast with flu-like symptoms and possibly fever — see your provider the same day.

Sources: ABM Protocol #26; ABM Protocol #2; LLLI "Sore Nipples."',
  'If you have a hard, warm, painful area in the breast with fever or flu-like symptoms, contact your care provider the same day — this may be mastitis, which requires treatment. Don''t wait to see if it resolves on its own.',
  NULL,
  'ABM Protocol #26; ABM Protocol #2; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-018',
  'Mastitis: the warning signs every nursing mom should know now',
  'Mastitis — a breast infection — most commonly strikes in the first 2–6 weeks. Most moms who get it didn''t see it coming. Knowing the early signs can get you treated faster and back to feeding sooner. Want to know what to watch for?',
  'Mastitis is an inflammation of breast tissue, usually involving infection. It affects roughly 10% of breastfeeding moms, most commonly in weeks 2–6 but possible any time.

Early warning signs (don''t wait to act):
— A localized area of redness, warmth, or hardness in one breast
— Breast pain that feels different from normal fullness or engorgement
— Flu-like symptoms: fatigue, body aches, chills — these often precede the breast symptoms
— Fever above 100.4°F

What to do immediately:
— Keep feeding or pumping. Stopping makes mastitis worse. The breast needs to be emptied regularly.
— Rest (genuinely), stay hydrated, and take ibuprofen to manage inflammation and fever
— Apply warm compress before feeds to encourage milk flow
— Contact your OB or care provider the same day — most mastitis requires antibiotics

Mastitis is not a reason to stop breastfeeding. Milk is safe for the baby even during infection. Sources: ABM Protocol #36 (mastitis); ABM Protocol #2; LLLI.',
  'Mastitis requires same-day contact with your care provider. Untreated mastitis can progress to a breast abscess, which is much harder to treat. If you have fever, breast redness, and flu-like symptoms, call your OB today — don''t wait for a scheduled appointment.',
  NULL,
  'ABM Protocol #36; ABM Protocol #2; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-019',
  'Setting up your pump schedule: what matters most right now',
  'If you''re exclusively pumping, the schedule you set in the first few weeks directly affects your long-term supply. The timing and frequency matter more than duration right now. Here''s what to aim for.',
  'For exclusive pumpers, the first 6 weeks are the supply-establishment window — what you do now calibrates your baseline.

Frequency targets:
— Weeks 1–2: aim for 8–10 pump sessions per 24 hours. Yes, this includes at least one overnight session (typically around 3am) when prolactin is highest.
— Weeks 3–6: you can gradually reduce to 7–8 sessions as supply establishes, if output is where you want it.
— After week 6–8: many moms can reduce to 6–7 sessions once supply is regulated.

Duration: pump until the milk slows significantly, then 2 more minutes ("pumping to empty" matters more than watching a clock). Most sessions run 15–20 minutes on each side.

Single vs. double pump: double pumping is strongly preferred — it is more effective, takes half the time, and produces higher prolactin stimulation. If you only have a single pump, prioritize getting a double.

Hands-on pumping: using breast compression while pumping increases output by 25–50% in studies. Compress and massage one breast at a time while the pump runs.

Sources: ABM Protocol #32 (exclusive pumping); Hale''s Medications and Mothers'' Milk; published exclusive pumping literature.',
  NULL,
  NULL,
  'ABM Protocol #32; published EP literature',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-020',
  'Flange size: your pump output depends on getting this right',
  'Flange size is one of the most commonly missed variables in pumping — and wrong sizing causes both lower output and nipple pain. Most moms are using the wrong size. Here''s how to check.',
  'Flanges (also called breast shields) are the funnel-shaped pieces that fit over your nipple and areola. If the tunnel diameter is wrong, the pump can''t create effective suction and your nipple can be damaged.

How to measure: use a ruler to measure the diameter of your nipple at its base (not the areola). The flange tunnel diameter should be 1–2mm larger than your nipple diameter. Most pumps come with 24mm and 27mm flanges; nipple diameters typically range from 13mm to 21mm. Many moms need a smaller flange than what comes in the box.

Signs your flange is too large: areola is being pulled into the tunnel, pinching sensation during pumping, low output.
Signs your flange is too small: nipple rubs against the tunnel walls, friction or pain, limited nipple movement.

Breast size and flange size are unrelated. A mom with larger breasts may need a smaller flange and vice versa. Nipples can also change size slightly over the course of pumping — recheck sizing if output drops or pain develops.

Many pump brands offer additional sizes. An IBCLC specializing in pumping can measure and fit flanges in a single visit. Sources: Flange sizing guidance from Medela, Spectra, Elvie, and Motif; ABM Protocol #32; published pumping literature.',
  NULL,
  NULL,
  'ABM Protocol #32; manufacturer sizing guides; IBCLC consensus',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-021',
  'Power pumping: what it is and when it actually helps',
  'Power pumping is a technique used to simulate cluster feeding — it sends a strong demand signal to your body to increase supply. It''s not magic, and it won''t help every situation. But if your supply has plateaued and your schedule and flange size are already dialed in, it''s worth understanding.',
  'Power pumping mimics the cluster feeding a nursing baby does during a growth spurt. One common protocol: pump 20 minutes, rest 10, pump 10, rest 10, pump 10 — 60 minutes total, replacing one regular pump session. Do this once per day for 3–7 consecutive days.

When power pumping helps: when supply has plateaued despite adequate session frequency and good flange fit; during or after illness or a significant reduction in sessions; after a period of stress or poor sleep that temporarily reduced output.

When it doesn''t help: if the underlying issue is anatomical (IGT, breast surgery) or hormonal, power pumping cannot override that. If flange size is wrong, power pumping with poor fit will cause pain and may not help output.

Before trying power pumping: confirm flange size is correct, confirm session frequency is at least 7–8 per 24 hours, and confirm you''re pumping to empty each session. These are more reliably effective than power pumping alone.

Sources: ABM Protocol #32; published exclusive pumping literature.',
  NULL,
  NULL,
  'ABM Protocol #32; published EP literature',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-022',
  'Freezer stash: what a healthy buffer actually looks like',
  'A lot of pumping moms feel like they need a huge freezer stash to feel secure. The anxiety about the stash can take over. Here''s a more grounded way to think about it.',
  'A freezer stash is a safety buffer — not a measure of success or how much you love your baby. Most families don''t need a massive stash, and obsessing over building it can lead to oversupply issues.

A functional buffer: 3–5 days of your baby''s daily intake is a realistic and adequate working stash for most families. At 8 weeks, a baby typically takes 3–4 oz per feed and feeds 8–10 times per day — roughly 25–30 oz/day. A buffer of 75–150 oz is genuinely protective without requiring heroic pumping effort.

How to build it without burning out: if you''re consistently making slightly more than your baby needs, freeze the daily surplus rather than adding extra sessions. One extra pump session per day after the first morning feed (typically the highest-output session) is a sustainable approach.

Oversupply is its own problem: moms who pump aggressively beyond demand can develop chronic engorgement, recurrent plugged ducts, and mastitis. Bigger is not always better.

Storage math: milk in the back of a chest freezer at 0°F keeps for up to 12 months. Label each bag with date and volume. Rotate older bags to the front.

Sources: CDC human milk storage guidelines; ABM Protocol #32.',
  NULL,
  NULL,
  'CDC milk storage guidelines; ABM Protocol #32',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-023',
  'A note about your anatomy and supply — worth knowing early',
  'Based on what you shared about your breast anatomy, you may want to monitor your supply more closely in the first two weeks than the average mom. This doesn''t mean something will go wrong — but catching any concerns early makes them much more manageable.',
  'Both breast reduction surgery and hypoplastic/tubular breasts (Insufficient Glandular Tissue, or IGT) can affect the amount of milk-producing tissue available and the nerve pathways that drive the letdown reflex.

Brest reduction: the most common supply risk of any breast surgery. Outcomes depend heavily on the surgical technique — pedicle-based procedures that preserved the nipple attachment tend to have better outcomes than free nipple grafts. Some moms after reduction achieve full supply; many produce partial supply and successfully combo feed.

Hypoplastic breasts / IGT: the breast tissue present may simply produce less milk than a baby requires, and this often does not respond to increased feeding frequency or pumping the way typical low supply does. Signs that may suggest IGT include widely spaced breasts, disproportionately large areolas, a tubular breast shape, and minimal breast growth during pregnancy.

For both situations: the most important steps are (1) work with an IBCLC in the first week — don''t wait to see if supply is adequate; (2) monitor infant weight closely at the 5-day and 2-week checks; (3) have a combo feeding plan ready as a real and valid option, not a fallback.

Sources: ABM Protocol #2; ABM Protocol #9; Marasco & West "Making More Milk"; published IGT literature.',
  'If your baby is not regaining birth weight by day 10–12 or is showing signs of insufficient intake (fewer than 6 wet diapers, lethargic, not back to birth weight by 2 weeks), see an IBCLC and your pediatrician the same week — earlier than you might otherwise. Early intervention protects both supply and your baby''s growth.',
  NULL,
  'ABM Protocol #2; ABM Protocol #9; Marasco & West; published IGT literature',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-024',
  'Getting a latch with flat or inverted nipples: a heads up before day one',
  'Getting a latch established with flat or inverted nipples can take a little more effort than average — but many moms do it successfully. Knowing a few techniques before you''re in the delivery room makes a real difference.',
  'Flat or inverted nipples make it harder for the baby to get a clear latch target, but they don''t prevent breastfeeding. Effective techniques:

Draw out the nipple before latching: use a pump on the lowest setting for 1–2 minutes immediately before a feed. This temporarily elongates the nipple and gives the baby something to latch onto. Hoffman''s exercises (gentle stretching) can also help, though evidence is mixed.

Breast sandwich: compress the breast tissue to create a more defined shape — like compressing a hamburger before taking a bite. This helps the baby get a deeper, more complete mouthful.

Nipple shield: a silicone shield worn over the nipple provides a firmer target for the baby to latch onto. Use with IBCLC guidance to confirm correct size and adequate milk transfer — shields can reduce milk flow if used incorrectly. They are a bridge tool, not a forever solution.

Positioning: the football hold gives you the most control over the baby''s head positioning and approach angle, which is especially useful with latch challenges.

For inverted nipples: the degree of inversion matters. Grade 1 (inverts but can be pulled out) responds well to the techniques above. Grade 3 (deeply inverted, does not evert) almost always benefits from IBCLC involvement from the first day — ideally a prenatal consultation.

Sources: ABM Protocol #2; ABM Protocol #11; LLLI latch guidance.',
  'If you have deeply inverted nipples (grade 3) or if latching is not improving by day 3–4 despite trying these techniques, request a lactation consult in the hospital before discharge. The earlier the intervention, the better the outcome.',
  NULL,
  'ABM Protocol #2; ABM Protocol #11; LLLI',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'AG-025',
  'A note about breastfeeding and your implants',
  'Most moms with breast implants breastfeed successfully, but the surgical history matters more than the implants themselves. Here''s what''s worth knowing — and what to watch for — in the first couple of weeks.',
  'Whether breast implants affect supply depends primarily on the surgical approach, not the implants themselves:

Incision type matters most: periareolar incisions (around the areola) carry the highest risk of disrupting milk ducts and the nerves responsible for letdown. Inframammary (breast fold) and axillary (armpit) incisions carry lower risk.

Implant placement: subglandular implants (over the muscle, directly under breast tissue) sit closest to glandular tissue and may compress it, potentially reducing functional tissue. Submuscular implants (under the pectoralis muscle) are further from glandular tissue and generally associated with lower breastfeeding impact.

What to do: tell your IBCLC and your baby''s pediatrician about your implant history before birth. Most will recommend closer supply and weight monitoring in the first 1–2 weeks rather than assuming everything is fine. Many moms with implants achieve full supply — but discovering a supply challenge at 3 weeks instead of 1 week costs valuable time.

You can find your surgical details (incision type, implant placement, implant type) in your plastic surgeon''s records if you don''t remember them.

Sources: ABM Protocol #2; published literature on breast implants and lactation (Semple et al.; Jewell et al.).',
  'Ask your IBCLC or pediatrician to monitor supply and weight gain more closely in the first two weeks if you have implants. Don''t wait for a weight gain concern to come up at the scheduled 2-week visit — request a weight check at day 5–7 if possible.',
  NULL,
  'ABM Protocol #2; published implants and lactation literature',
  NULL,
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
-- ─── MILESTONE MEMORY (ML) ───────────────────────────────────────

INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-001',
  'First 24 hours complete',
  'You just got through the first 24 hours. Whether you''re still in the hospital or already home, this was the hardest day — your body was figuring it out, your baby was figuring it out, and nobody had any certainty about how it was going to go. You kept going anyway. That counts.',
  NULL,
  NULL,
  'Day one is done. My baby is fed and so am I.',
  NULL,
  'Fire once, silently (no push notification). Surfaces the next time mom opens the app within the first 48 hours. Tone: quiet acknowledgment, not celebration — day one often feels hard, not triumphant.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-002',
  'One week in',
  'One week. Do you know how many people don''t make it to one week? A lot. The first week of feeding a newborn is genuinely one of the hardest things — the learning curve is steep, sleep is gone, and your body is healing at the same time. You''ve been feeding your baby for seven days straight. That''s not small.',
  NULL,
  NULL,
  'One week of feeding my baby. Every single day.',
  NULL,
  'Good candidate for the first milestone that surfaces a ''look back'' callback if there is prior chat history — e.g., ''A week ago you said [thing from day 1]. Look where you are now.''',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-003',
  'Two weeks in — birth weight milestone',
  'Two weeks. Your baby has (most likely) regained their birth weight, which means your body has been their entire food source and it''s working. Every middle-of-the-night session, every engorged morning, every time you weren''t sure it was enough — it was enough. Your baby is growing.',
  NULL,
  NULL,
  'Two weeks in. My baby is back to their birth weight and then some.',
  NULL,
  'If birth-weight-regained is confirmed via chat or user input, message should reference it explicitly: ''Your baby is back to their birth weight.'' If not confirmed, use hedged language: ''Your baby has (most likely) regained...'' Do not state it as fact without confirmation.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-004',
  'One month',
  'One month. The version of you who left the hospital did not know if you could do this for a month. Now you know. You''ve been your baby''s food source for thirty days — through the engorgement, through the growth spurts, through whatever hard thing happened in the middle that you got through anyway. A month is real.',
  NULL,
  NULL,
  'One month of feeding my baby. I wasn''t sure I could do it. I did.',
  NULL,
  'This is the milestone most moms explicitly set as a goal in the first week. If the user mentioned a specific goal in chat (e.g., ''I just want to make it a month''), this message should reference it directly.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-005',
  'Six weeks',
  'Six weeks. This is the milestone that gets set in week one when everything feels impossible and you''re just trying to find a number you can survive to. You made it here. The hardest physiological adjustment period is behind you. Your body and your baby have figured each other out in ways that weren''t true a month ago. Whatever happens from here — you got here.',
  NULL,
  NULL,
  'Six weeks. This was the goal I set when I wasn''t sure I could. I made it.',
  NULL,
  'Six weeks is the single most-cited goal milestone in early breastfeeding research. High emotional resonance. Good candidate for the share mechanic — ''Send this to someone who''s been cheering you on.''',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-006',
  'Two months',
  'Two months. Your baby is different than they were at birth — more alert, more themselves — and you''ve been feeding them every step of the way. You''ve figured out each other''s rhythms. You''ve made it through at least two growth spurts. Whatever the early weeks threw at you, you''ve adapted. That took time and patience and more nights than you can count.',
  NULL,
  NULL,
  'Two months in. We''ve got each other figured out.',
  NULL,
  'Can optionally surface a ''remember when'' callback if chat history includes a day-1 or week-1 message.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-007',
  'Three months — the click',
  'Three months. Most moms who make it here say — later, looking back — that this was when it finally clicked. When feeding started to feel less like a thing they were doing and more like something that just... belonged to them and their baby. You might be there already. You might get there next week. Either way: three months is yours. You earned it.',
  NULL,
  NULL,
  'Three months of breastfeeding. This is when people say it finally clicks. I think I understand what they meant.',
  NULL,
  'Three months is the research-backed inflection point where breastfeeding confidence scores improve sharply. Highest-signal milestone for retention — moms who reach 3 months continue at a much higher rate. Premium treatment in the UI: slightly more prominent than other milestones.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-008',
  'Six months — AAP milestone',
  'Six months. Six months of your body being your baby''s food source — or a major part of it. The AAP recommends exclusive breastfeeding for six months; pediatricians cite it as a landmark. But you weren''t doing it for the recommendation. You were doing it for your baby, one day at a time, and you made it half a year. That''s not nothing. That''s actually everything.',
  NULL,
  NULL,
  'Six months of feeding my baby. Half a year. I didn''t count the days — I just kept going.',
  NULL,
  'Note: if user is combo feeding, the message should acknowledge that explicitly — ''six months of your body being a major part of your baby''s food source'' rather than ''entire food source.'' Feeding preference flag should be read at trigger time.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-009',
  'First successful latch',
  'There it is. Your baby just latched — really latched. That sound, or that feeling, or that look on their face — that''s what you were working toward. The early latching stage is one of the technically hardest parts of nursing, and you got through it. It will be easier from here.',
  NULL,
  NULL,
  'My baby latched for the first time. We figured it out.',
  NULL,
  'This milestone may fire in the first hours or days, or it may fire weeks later after latch challenges. The message should feel the same either way — relief, not judgment. If the user mentions it took weeks, consider adding: ''It took as long as it took. You stayed with it.''',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-010',
  'First growth spurt survived',
  'Growth spurt: done. You just got through a few days of your baby acting like they''d completely forgotten how to be satisfied — wanting to eat constantly, fussier than usual, making you feel like your supply had disappeared. It hadn''t. Your supply heard the message loud and clear. Your body just calibrated up.',
  NULL,
  NULL,
  'First growth spurt: survived. My body figured it out.',
  NULL,
  'Growth spurt milestones are proxy-based (we can''t know for certain if the user experienced one). Use gentle phrasing: ''If you just came through a cluster feeding stretch...'' Consider making this user-confirmable rather than purely automatic.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-011',
  'Second growth spurt survived',
  'Second growth spurt behind you. This one probably still surprised you — even though you''d been through it before — because each one is its own thing. But notice: you knew what it was. You knew it was temporary. You kept going. That''s different from week three. You''ve learned your baby.',
  NULL,
  NULL,
  'Second growth spurt, done. Getting better at reading what my baby needs.',
  NULL,
  'The growth-spurt-to-growth-spurt callback is intentional — it reinforces learning and progress across the journey, not just at this moment.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-012',
  'First bottle of pumped milk',
  'Someone else just fed your baby with something you made. Think about that for a second. You pumped that. Your body made it. And now someone who loves your baby got to be part of feeding them. That''s not a backup plan — that''s your system working.',
  NULL,
  NULL,
  'My partner just fed our baby with milk I pumped. Team effort.',
  NULL,
  'For Path B (exclusive pumping) moms, this message should acknowledge that every feed has been pumped milk — adjust message accordingly: ''Every bottle your baby has had has been something you made. That''s the whole story.''',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-013',
  'First time feeding outside home',
  'You fed your baby outside your house. Maybe in a restaurant booth. Maybe in the car in a parking lot. Maybe at someone''s kitchen table while the rest of the meal happened around you. The world kept moving and so did you. That''s worth noting.',
  NULL,
  NULL,
  'Fed my baby out in the world today. We''re getting the hang of this.',
  NULL,
  'This milestone is pure positive reinforcement — no clinical weight, no escalation. Keep it warm and brief. The message should feel like a friend saying ''good for you'' without making it into more than it is.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-014',
  'Through a nursing strike',
  'Nursing strikes are the kind of thing that ends a lot of feeding journeys — because they feel personal, because the rejection is disorienting, because it is so hard to keep showing up when your baby keeps turning away. You figured it out. You didn''t take it personally (or you did, and you showed up anyway). Your baby is nursing again.',
  NULL,
  NULL,
  'We got through a nursing strike. My baby is nursing again.',
  NULL,
  'Nursing strike is emotionally high-stakes — some moms experience it as rejection or failure. The message should name that directly without amplifying it. The phrase ''you did, and you showed up anyway'' is an acknowledgment that it''s okay to have struggled emotionally.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-015',
  'Survived mastitis and kept going',
  'You had mastitis. You felt like you''d been hit by a truck — because you basically had been — and you kept feeding or pumping through it, which is the exact thing nobody tells you is both the treatment and the hardest possible thing to do when you''re that sick. You kept your baby fed and you kept your supply going. That''s a serious thing you just did.',
  NULL,
  NULL,
  'Had mastitis. Kept going anyway. Supply intact.',
  NULL,
  'Mastitis is one of the most commonly cited reasons moms stop breastfeeding earlier than intended. Acknowledging the difficulty explicitly and naming what they did right (kept feeding/pumping) is more valuable than generic encouragement. Only fire if user explicitly mentions mastitis — do not proxy from fever or breast pain mentions alone.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-016',
  'Supply regulated — past engorgement',
  'Your supply just regulated — or it''s in the process of doing it. A few weeks ago your breasts were unpredictably full, sometimes rock-hard, sometimes alarming. Now your body has figured out the schedule. It''s producing what your baby needs, roughly when they need it. You and your baby calibrated this together. That took weeks of consistent feeding and patience, and it worked.',
  NULL,
  NULL,
  'My body figured out the schedule. Supply regulated. We''re in sync now.',
  NULL,
  'This milestone pairs well with AG-008 (the supply regulation anticipatory message). If the user received AG-008 earlier and was reassured by it, this milestone closes the loop: ''Remember when your breasts started feeling softer and we talked about why? That process is done.''',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-017',
  'Kept supply through illness',
  'You were sick — really sick — and you kept feeding or pumping anyway. That is genuinely hard to do. When your body is using all its resources to fight an illness, keeping supply going takes everything you have left. Your supply made it through. So did you.',
  NULL,
  NULL,
  'Got sick. Kept going. Supply is still there.',
  NULL,
  'Keep this one short. When someone is coming out of illness, they don''t need a lot of words — they need acknowledgment that what they did was hard and it worked.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-018',
  'First day back at work pumping',
  'You pumped at work today. Maybe it was logistically complicated. Maybe you had to hunt for the room. Maybe it was emotionally harder than you expected — being physically separated from your baby and still doing this for them at the same time. You did it. One day is behind you. The second day will be easier than the first.',
  NULL,
  NULL,
  'Back at work. Still pumping for my baby. Day one: done.',
  NULL,
  'Return to work is one of the top cited reasons for breastfeeding cessation. This milestone should feel like validation that the hard part (day one) is done, with quiet optimism about the path forward — not pressure to maintain the same level indefinitely.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-019',
  'Navigated the combo feeding decision',
  'You made the call to combo feed — and you made it intentionally, on your terms. That decision is more considered than most people give it credit for. It means your baby is fed. It means you''re still in this, doing the parts that work for your family. Whatever the mix looks like, it''s yours. It counts.',
  NULL,
  NULL,
  'Combo feeding: my terms, my baby, my family. It works for us.',
  NULL,
  'This milestone is specifically for the combo feeding without shame positioning. The message must never imply that combo feeding is a fallback or a lesser outcome. The word ''intentionally'' is load-bearing — it gives moms agency over a decision that is often framed as failure. Do not fire this message as a condolence.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-020',
  'One week of exclusive pumping',
  'One week of exclusive pumping. Seven days of every session, every day, at intervals that do not negotiate with your schedule, your sleep, or how you''re feeling. You built a supply this week. Your baby has been drinking something your body made, and you made it happen entirely through this process that is both mechanical and extraordinary. One week is real.',
  NULL,
  NULL,
  'One week of exclusive pumping. Every session, every day. My baby is fed.',
  NULL,
  'EP moms are often invisible in breastfeeding support content. This milestone should name what EP actually involves — the sessions, the schedule, the labor — rather than treating it as a lighter version of nursing. Language: extraordinary, real, every session.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-021',
  '30 days of exclusive pumping',
  'Thirty days of exclusive pumping. Thirty days of sessions that happen whether you feel like it or not — at 3am, between other things, when you''re tired or engorged or just over it. You have done this every single day for a month and your baby has been fed every single day because of it. Say it to yourself, out loud if you want: extraordinary. Because it is.',
  NULL,
  NULL,
  '30 days of exclusive pumping. One month. Every session, for my baby.',
  NULL,
  '30 days is a significant EP milestone — many EP moms who make it 30 days continue for much longer. The tone should reflect that this is a real achievement, not a stepping stone. The instruction ''say it out loud'' is intentional — it''s a prompt toward self-acknowledgment, not performance for others.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-022',
  'First freezer stash bag',
  'First bag in the freezer. You made more than your baby needed today, and now there''s a little insurance policy in there with today''s date on it. That bag is real. You made that. And there will be more.',
  NULL,
  NULL,
  'First bag in the freezer. Building something for my baby, one bag at a time.',
  NULL,
  'Keep this one short and warm. The freezer stash has significant anxiety attached for EP moms — this milestone should feel like relief and progress, not pressure to keep building a bigger stash. The phrase ''there will be more'' is a gentle forward orientation.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-023',
  'Double-digit daily output achieved',
  'Your output cleared double digits today. Your body figured this out — sessions, compression, schedule, all of it adding up. There will still be low-output days, but today was a proof point: the system is working. You built this.',
  NULL,
  NULL,
  'Body figured out the supply. We''re in business.',
  NULL,
  '10 oz/day is an EP-specific milestone that many moms track closely in the first 2 weeks. The message should acknowledge the work that got there (schedule, technique) without implying that more is always better. Include a caveat about variable days so moms don''t panic when output fluctuates.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-024',
  'Reached your original goal',
  'You said you wanted to make it to [GOAL]. You''re here. The version of you who set that goal — in week one, when you weren''t sure you could make it — set a real goal and then actually did it. Whatever comes next is a bonus. This is the thing you said you''d do.',
  NULL,
  NULL,
  'I set a goal. I made it. [GOAL] of feeding my baby.',
  NULL,
  '[GOAL] should be populated from user''s stated goal if captured during onboarding or in early chat (e.g., ''6 weeks'', ''3 months'', ''until I go back to work''). If no goal was stated, use a fallback: ''You''ve been feeding your baby for [X weeks], and whatever goal you had in mind when you started — you''re on the other side of it now.'' This is the most personalized milestone in the library.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-025',
  'Extended past original goal',
  'You said [GOAL] and then you just... kept going. That wasn''t the plan, or maybe it became the plan. Either way: every day past your original goal is a day you chose to keep doing this. Not because you had to. Because it was still working for you and your baby. That''s worth acknowledging.',
  NULL,
  NULL,
  'I made my goal. Then I kept going.',
  NULL,
  'This milestone should feel quiet and warm — not triumphant. Some moms extend reluctantly (because they feel they ''should'') and some extend because they genuinely want to. The message should honor both without implying either is right.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-026',
  'Choosing to wean',
  'You decided it''s time to wean. That decision is yours and it belongs entirely to you. Whatever brought you here — your body, your baby''s cues, your own needs, a timeline you set or a timeline that set itself — it doesn''t need to be justified. What matters is that you fed your baby in the way that worked for your family, for as long as it worked. That''s the whole story. And it''s a good one.',
  NULL,
  NULL,
  'I fed my baby for [X weeks/months]. It was the right decision for us. Starting to wean now.',
  NULL,
  'Weaning is one of the most emotionally complex moments in the breastfeeding journey — moms feel relief, grief, guilt, pride, and sadness often simultaneously. The message must be completely non-judgmental and non-clinical. Do NOT include any language about weaning ''too early'' or next steps for milk supply reduction unless the user asks. This moment is for acknowledgment, not guidance.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
INSERT INTO companion_content
  (trigger_id, headline, in_app_message, learn_more, escalation_text,
   share_card, sources, design_note, in_app_message_path_b, in_app_message_path_c)
VALUES (
  'ML-027',
  'Final session',
  'This is the last one. You''ll probably feel a lot of things right now — and not all of them will make sense. Relief and grief can sit in the same moment. Whatever you''re feeling is right. Every session before this one was real. Every bag in the freezer, every 3am pump, every latch you worked for — all of it was real. This one is too. You fed your baby. That''s a story that belongs to you.',
  NULL,
  NULL,
  'Last session. My baby is fed. I did this.',
  NULL,
  'The final session milestone deserves the most careful handling in the library. It should not be celebratory or sad — it should be present. The line ''relief and grief can sit in the same moment'' gives moms permission for complicated feelings without telling them what to feel. No guidance, no next steps. Just acknowledgment. Consider offering a ''save this moment'' option — a way to keep this message somewhere permanent, like a baby book.',
  NULL,
  NULL
) ON CONFLICT (trigger_id) DO UPDATE SET
  headline              = EXCLUDED.headline,
  in_app_message        = EXCLUDED.in_app_message,
  learn_more            = EXCLUDED.learn_more,
  escalation_text       = EXCLUDED.escalation_text,
  share_card            = EXCLUDED.share_card,
  sources               = EXCLUDED.sources,
  design_note           = EXCLUDED.design_note
  -- NOTE: path_b and path_c variants are NOT overwritten here.
  --       Update them separately once variant copy is written.
;
