-- companion_triggers seed
-- Generated by scripts/generate-companion-seed.js
-- Generated: 2026-05-31T22:48:18.329Z
-- DO NOT EDIT by hand — edit the content files and re-run the generator.

-- ─── ANTICIPATORY GUIDANCE (AG) — 25 entries ─────────────────────

INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-001',
  'AG',
  'time_based',
  NULL,
  0,
  2,
  NULL,
  NULL,
  NULL,
  40,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-002',
  'AG',
  'time_based',
  NULL,
  3,
  5,
  NULL,
  NULL,
  NULL,
  40,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-003',
  'AG',
  'time_based',
  NULL,
  5,
  7,
  NULL,
  NULL,
  NULL,
  40,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-004',
  'AG',
  'time_based',
  ARRAY['A','C'],
  12,
  14,
  NULL,
  NULL,
  NULL,
  45,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-005',
  'AG',
  'time_based',
  NULL,
  14,
  21,
  NULL,
  NULL,
  NULL,
  45,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-006',
  'AG',
  'time_based',
  NULL,
  18,
  21,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-007',
  'AG',
  'time_based',
  ARRAY['A','C'],
  28,
  42,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-008',
  'AG',
  'time_based',
  ARRAY['A','C'],
  40,
  45,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-009',
  'AG',
  'time_based',
  NULL,
  42,
  56,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-010',
  'AG',
  'time_based',
  NULL,
  56,
  70,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-011',
  'AG',
  'time_based',
  NULL,
  70,
  84,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-012',
  'AG',
  'time_based',
  NULL,
  80,
  84,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-013',
  'AG',
  'event_based',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-014',
  'AG',
  'event_based',
  NULL,
  12,
  14,
  NULL,
  NULL,
  NULL,
  45,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-015',
  'AG',
  'event_based',
  NULL,
  56,
  60,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-016',
  'AG',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['low supply','not enough milk','supply dropping','supply concern','not making enough','losing supply'],
  NULL,
  55,
  true
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-017',
  'AG',
  'chat_signal',
  ARRAY['A','C'],
  NULL,
  NULL,
  NULL,
  ARRAY['nipple pain','breast pain','sore nipple','cracked nipple','bleeding nipple','pain during nursing','hurts to nurse'],
  NULL,
  55,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-018',
  'AG',
  'profile_based',
  ARRAY['A','C'],
  14,
  42,
  NULL,
  NULL,
  NULL,
  45,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-019',
  'AG',
  'profile_based',
  ARRAY['B'],
  0,
  3,
  '{"feeding_preference":"exclusive_pumping","dob_offset_min":0,"dob_offset_max":3}'::jsonb,
  NULL,
  NULL,
  40,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-020',
  'AG',
  'profile_based',
  ARRAY['B'],
  7,
  14,
  '{"feeding_preference":"exclusive_pumping","dob_offset_min":7,"dob_offset_max":14}'::jsonb,
  NULL,
  NULL,
  40,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-021',
  'AG',
  'chat_signal',
  ARRAY['B'],
  NULL,
  NULL,
  NULL,
  ARRAY['low supply','not enough milk','supply dropping','supply concern','not making enough','losing supply'],
  NULL,
  55,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-022',
  'AG',
  'time_based',
  ARRAY['B'],
  28,
  28,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-023',
  'AG',
  'profile_based',
  NULL,
  NULL,
  NULL,
  '{"breast_anatomy_contains":["breast_reduction","hypoplastic_breasts"]}'::jsonb,
  NULL,
  NULL,
  50,
  true
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-024',
  'AG',
  'profile_based',
  ARRAY['A','C'],
  NULL,
  NULL,
  '{"breast_anatomy_contains":["flat_nipples","inverted_nipples"]}'::jsonb,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'AG-025',
  'AG',
  'profile_based',
  NULL,
  NULL,
  NULL,
  '{"breast_anatomy_contains":["breast_implants","breast_augmentation"]}'::jsonb,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
-- ─── MILESTONE MEMORY (ML) — 27 entries ──────────────────────────

INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-001',
  'ML',
  'time_based',
  NULL,
  1,
  1,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-002',
  'ML',
  'time_based',
  NULL,
  7,
  7,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-003',
  'ML',
  'time_based',
  NULL,
  14,
  14,
  NULL,
  NULL,
  NULL,
  55,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-004',
  'ML',
  'time_based',
  NULL,
  30,
  30,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-005',
  'ML',
  'time_based',
  NULL,
  42,
  42,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-006',
  'ML',
  'time_based',
  NULL,
  60,
  60,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-007',
  'ML',
  'time_based',
  NULL,
  84,
  84,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-008',
  'ML',
  'time_based',
  NULL,
  180,
  180,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-009',
  'ML',
  'chat_signal',
  ARRAY['A','C'],
  NULL,
  NULL,
  NULL,
  ARRAY['first latch','latch finally worked','latched for the first time','or similar language'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-010',
  'ML',
  'time_based',
  NULL,
  21,
  24,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-011',
  'ML',
  'time_based',
  NULL,
  56,
  60,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-012',
  'ML',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['partner feeding  someone else gave a bottle  first bottle','or pump_model is set','baby_dob  21 days'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-013',
  'ML',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['feeding at a restaurant','in public','at someones house','in the car','outside','etc'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-014',
  'ML',
  'chat_signal',
  ARRAY['A','C'],
  NULL,
  NULL,
  NULL,
  ARRAY['nursing strike resolved','baby is nursing again','baby finally latched after refusing'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-015',
  'ML',
  'chat_signal',
  ARRAY['A','C'],
  NULL,
  NULL,
  NULL,
  ARRAY['mastitis resolved','antibiotics finished','feeling better after mastitis'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-016',
  'ML',
  'time_based',
  NULL,
  42,
  50,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-017',
  'ML',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['being sick','continuing','supply survived illness','pumping while sick','being sick and continuing'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-018',
  'ML',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['pumping at work','first day back','returning to work','pumped'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-019',
  'ML',
  'chat_signal',
  ARRAY['C'],
  NULL,
  NULL,
  NULL,
  ARRAY['deciding to add formula  transition to combo'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-020',
  'ML',
  'time_based',
  ARRAY['B'],
  7,
  7,
  NULL,
  NULL,
  NULL,
  50,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-021',
  'ML',
  'time_based',
  ARRAY['B'],
  30,
  30,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-022',
  'ML',
  'chat_signal',
  ARRAY['B'],
  NULL,
  NULL,
  NULL,
  ARRAY['first freezer bag','first stash','put milk in the freezer for the first time'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-023',
  'ML',
  'time_based',
  ARRAY['B'],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-024',
  'ML',
  'chat_signal',
  NULL,
  42,
  42,
  NULL,
  NULL,
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-025',
  'ML',
  'goal_comparison',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  7,
  60,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-026',
  'ML',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['deciding to wean','starting weaning process','done breastfeeding  pumping','stopping'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
INSERT INTO companion_triggers
  (id, feature, trigger_type, paths, dob_offset_min, dob_offset_max,
   profile_conditions, chat_signal_keywords, goal_threshold_days, priority, held)
VALUES (
  'ML-027',
  'ML',
  'chat_signal',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['last pump session','last nursing session','done','final feed','all done'],
  NULL,
  65,
  false
) ON CONFLICT (id) DO UPDATE SET
  feature = EXCLUDED.feature,
  trigger_type = EXCLUDED.trigger_type,
  paths = EXCLUDED.paths,
  dob_offset_min = EXCLUDED.dob_offset_min,
  dob_offset_max = EXCLUDED.dob_offset_max,
  profile_conditions = EXCLUDED.profile_conditions,
  chat_signal_keywords = EXCLUDED.chat_signal_keywords,
  goal_threshold_days = EXCLUDED.goal_threshold_days,
  priority = EXCLUDED.priority
  -- NOTE: held is intentionally NOT updated on conflict
  --       to preserve manual HOLD clearances.
;
